version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.01

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - .node_modules
      - run: yarn test